### PR TITLE
Fix OpenSSL::SSL::SSLContext::METHODS deprecation warning in Ruby 2.5

### PR DESCRIPTION
**Pull request by daveallie**
In Ruby 2.5 the follow deprecation message is provided when trying to create a `Le` instance with SSL.
 
`lib/le/host/http.rb:191: warning: constant OpenSSL::SSL::SSLContext::METHODS is deprecated`

Use the `METHODS_MAP` constant instead.

### CODE REVIEW

**Comment by JoeMcB** [comment]
This is flooding our logs as well, so this should be merged in ASAP.

**Comment by imnotquitejack** [comment]
Any plans to merge this?  @eshanley-r7 @gcurran-r7

**Comment by semaperepelitsa** [comment]
I believe the correct solution is to use new min_version/max_version attributes, not another constant. See https://github.com/ruby/openssl/pull/142/files

**Comment by semaperepelitsa** [comment]
Something like

```ruby
ssl_context.min_version = :TLSv1
ssl_context.max_version = :TLSv1_2
```

**Comment by sbialkowski-r7** [comment]
This gem has been deprecated and will not be updated.
This issue has been resolved in: `r7insight:3.0.0`
https://github.com/rapid7/r7insight_ruby/releases/tag/3.0.0

**Pull request closed without merging**
